server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass https://vmtips-production-7181.up.railway.app/api/;
        proxy_set_header Host DIN-BACKEND-URL.up.railway.app;
        proxy_ssl_server_name on;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}